alias mp="cd ~/drive/projects/github/WelcometoMoonPrison-tmh/"
alias gpr="git pull --rebase"
alias py="python3"

alias re="rtv --enable-media"
alias fs="ranger"
alias calc="concalc"
alias neo="nvim"

alias c="clear"
alias hm="cd ~"
alias uwa="cd ~/drive/.uwa/"
alias thesis="cd ~/drive/.uwa/thesis/"
alias dp="cd ~/drive/.uwa/ELEC5552/"
alias q="exit"

alias tl="task list"
alias tcal="task calendar"
alias ta="task add"
alias tm="task modify"
alias td="task done"
alias tu="task ready"

alias apt="sudo apt-get"
alias pip="sudo pip"

alias ftl="./games/ftl/start.sh"
alias oxenfree="./games/oxenfree/start.sh"
alias jotun="./games/jotun/start.sh"
alias satreign="./games/satreign/start.sh"
